### ISSUE TITLE
Customize tag field "_tag"

### ISSUE THREAD

**Issue by baranyildirim** [jasonkuhrt/alge#365]
Hey 👋 
Thanks for creating this awesome library.

Is it possible to change the name of the tag field for JSON codecs?
I want to use a different name for the field and not "_tag". It's not a hard blocker but just wanted to check if there is a configuration option that supports this.

**Comment by jasonkuhrt** [comment]
Hey @baranyildirim. I would be open to a feature making this possible. I am not sure when I would get around to it personally. PR welcome once an API design is agreed upon.
